<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>pdfgestor</AssemblyName>
    <RootNamespace>PdfGestor.Cli</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfGestor.Core\PdfGestor.Core.csproj" />
  </ItemGroup>

</Project>
